-- DROP TABLE
DROP TABLE CONTACT;
DROP TABLE NOTICE;
DROP TABLE LOCAL_PET
DROP TABLE ADMIN;
DROP TABLE REVIEW;
DROP TABLE CUSTOMER_PET;
DROP TABLE MEMBER;

-- DROP SEQUENCE
DROP SEQUENCE CUSTOMER_PET_SEQ;
DROP SEQUENCE REVIEW_SEQ;
DROP SEQUENCE NOTICE_SEQ;
DROP SEQUENCE ADMIN_SEQ;
DROP SEQUENCE LOCAL_PET_SEQ;
DROP SEQUENCE CONTACT_SEQ;
-- CREATE SEQUENCE
CREATE SEQUENCE CUSTOMER_PET_SEQ MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE REVIEW_SEQ MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE NOTICE_SEQ MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE ADMIN_SEQ MINVALUE 100001 MAXVALUE 999999 NOCYCLE NOCACHE;
CREATE SEQUENCE LOCAL_PET_SEQ MAXVALUE 99999 NOCYCLE NOCACHE;
CREATE SEQUENCE CONTACT_SEQ MAXVALUE 99999 NOCYCLE NOCACHE;

-- CREATE TABLE
CREATE TABLE MEMBER (
  ID VARCHAR2(20) PRIMARY KEY,
  PW VARCHAR2(30) NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  LOCTEL VARCHAR2(5) NOT NULL,
  MIDTEL VARCHAR2(5) NOT NULL,
  LASTEL VARCHAR2(5) NOT NULL,
  EMAIL VARCHAR2(50) NOT NULL,
  ADDRESS VARCHAR2(200),
  NICKNAME VARCHAR2(50),
  REGIDATE DATE DEFAULT SYSDATE NOT NULL,
  ACCOUNT_STATUS NUMBER(1) NOT NULL
);
CREATE TABLE ADMIN (
  COMNO NUMBER(6) PRIMARY KEY,
  COMNAME VARCHAR2(50) NOT NULL,
  COMDATE DATE DEFAULT SYSDATE NOT NULL,
  COMEMAIL VARCHAR2(100) NOT NULL,
  COM_STATUS NUMBER(1) NOT NULL
);
CREATE TABLE LOCAL_PET (
  PETID NUMBER(5) PRIMARY KEY,
  COMNO NUMBER(6) REFERENCES ADMIN(COMNO) NOT NULL,
  PETTYPE VARCHAR2(30) NOT NULL,
  PETBRADS VARCHAR2(50) NOT NULL,
  PETNAME VARCHAR2(100) NOT NULL,
  PETAGE NUMBER(2) NOT NULL,
  PETPRICE NUMBER(10),
  PETIMG VARCHAR2(100) NOT NULL,
  PETUPDATE DATE DEFAULT SYSDATE NOT NULL,
  PET_STATUS NUMBER(1) NOT NULL
);
CREATE TABLE CONTACT (
  CID NUMBER(5) PRIMARY KEY,
  CWRITER VARCHAR2(100) NOT NULL,
  CTITLE VARCHAR2(200) NOT NULL,
  CTEXT VARCHAR2(4000) NOT NULL,
  CDATE DATE DEFAULT SYSDATE NOT NULL,
  CGROUP NUMBER(5) NOT NULL,
  CSTEP NUMBER(5) NOT NULL,
  CINDENT NUMBER(5) NOT NULL,
  CIP VARCHAR2(30) NOT NULL,
  CDATA_STATUS NUMBER(1) NOT NULL
);
CREATE TABLE  NOTICE (
  NID NUMBER(5) PRIMARY KEY,
  COMNO NUMBER(6) REFERENCES ADMIN(COMNO) NOT NULL,
  NDATE DATE DEFAULT SYSDATE NOT NULL,
  NTITLE VARCHAR2(200) NOT NULL,
  NTEXT VARCHAR2(4000) NOT NULL,
  NIMG VARCHAR2(200),
  NIP VARCHAR2(30)
);
CREATE TABLE REVIEW (
  RID NUMBER(5) PRIMARY KEY,
  ID VARCHAR2(20) REFERENCES MEMBER(ID) NOT NULL,
  RDATE DATE DEFAULT SYSDATE NOT NULL,
  RTITLE VARCHAR2(200) NOT NULL,
  RTEXT VARCHAR2(4000) NOT NULL,
  RIMG VARCHAR2(200),
  RIP VARCHAR2(30) NOT NULL,
  RDATA_STATUS NUMBER(1) NOT NULL
);

CREATE TABLE CUSTOMER_PET (
  PETNO NUMBER(5) PRIMARY KEY,
  ID VARCHAR2(20) REFERENCES MEMBER(ID) NOT NULL,
  ANAME VARCHAR2(100),
  ADATE DATE
);

-- TABLE CHECK
SELECT * FROM ADMIN;ㅑㅇ
SELECT * FROM LOCAL_PET;
SELECT * FROM REVIEW;
SELECT * FROM NOTICE;
SELECT * FROM CONTACT;
SELECT * FROM CUSTOMER_PET;
SELECT * FROM MEMBER;