-- DUMMY DATA INSERT
INSERT INTO ADMIN VALUES(ADMIN_SEQ.NEXTVAL, '홍길동', SYSDATE, 'admin@dog@net', 1);
INSERT INTO MEMBER VALUES('kim12345', '12345678', '김길동', '010','1234','5678','kim@naver.com','서울 송파구','아빠',SYSDATE,1);
INSERT INTO CUSTOMER_PET VALUES(CUSTOMER_PET_SEQ.NEXTVAL, 'kim12345','나비','2014/01/01');
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 'kim12345',SYSDATE, '제목테스트','본문테스트',NULL,'124.0.0.1',1);
INSERT INTO NOTICE VALUES (NOTICE_SEQ.NEXTVAL, 100001, SYSDATE, '공지사항 테스트', '본문 테스트', NULL, '198.55.45.8');
INSERT INTO CONTACT VALUES (CONTACT_SEQ.NEXTVAL, 'TESTER', '문의글 테스트', '본문 테스트', SYSDATE, CONTACT_SEQ.CURRVAL, 0,0, '192.168.0.1', 1);
INSERT INTO LOCAL_PET VALUES(LOCAL_PET_SEQ.NEXTVAL, 100001, '강아지', '포메라니안', '초코', 1, 50, 'CHOCO.PNG', SYSDATE, 1);

-- DUMMY CHECK
SELECT * FROM ADMIN;
SELECT * FROM LOCAL_PET;
SELECT * FROM REVIEW;
SELECT * FROM NOTICE;
SELECT * FROM CONTACT;
SELECT * FROM CUSTOMER_PET;
SELECT * FROM MEMBER;

